swagger: "2.0"
info:
  description: Garden Buddy Backend Swagger file
  version: "1.0.0"
  title: Garden Buddy Backend Swagger file
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /users:
    get:
      operationId: "users.getAllUsers"
      tags:
        - "User"
      summary: "Get all users in Garden Buddy"
      description: "Retrieve the list of users"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/User"

definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      password:
        type: "string"
      firstname:
        type: "string"
      lastname:
        type: "string"
      user_start_date:
        type: "string"
        format: "date-time"
  GardenBuddy:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      date_registered:
        type: "string"
        format: "date-time"
      user_id:
        type: "integer"
        format: "int64"
  Garden:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      garden_buddy_id:
        type: "integer"
        format: "int64"
      garden_type_id:
        type: "integer"
        format: "int64"
  GardenImage:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      garden_image_link:
        type: "string"
      timestamp:
        type: "string"
        format: "date-time"
      garden_id:
        type: "integer"
        format: "int64"
  GardenData:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      soil_ph_level:
        type: "integer"
      air_temperature:
        type: "integer"
      soil_salinity:
        type: "integer"
      soil_moisture:
        type: "integer"
      date_timestamp:
        type: "string"
        format: "date-time"
      garden_id:
        type: "integer"
        format: "int64"
  GardenType:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      plant_name:
        type: "string"
      plant_description:
        type: "string"
      ideal_ph_level:
        type: "integer"
      ideal_temp_level:
        type: "integer"
      ideal_moisture_level:
        type: "integer"
      ideal_soil_salinity:
        type: "integer"
  Order:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      total_price:
        type: "integer"
      order_status_enum:
        type: "string"
        enum:
          - "ORDER_PLACED"
          - "IN_TRANSIT"
          - "DELIVERED"
      user_id:
        type: "integer"
        format: "int64"
  OrderLineItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      quantity:
        type: "integer"
      sub_total:
        type: "integer"
      order_id:
        type: "integer"
        format: "int64"
      inventory_item_id:
        type: "integer"
        format: "int64"
  InventoryItem:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      price:
        type: "integer"
      quantity:
        type: "integer"
      description:
        type: "string"
      type:
        type: "string"
  GardenBuddyPack:
    type: "object"
    allOf:
      - $ref: "#/definitions/InventoryItem"
    properties:
      plant_name:
        type: "string"
      garden_buddy_pack_description:
        type: "string"
      environment_enum:
        type: "string"
        enum:
          - "FOREST"
          - "TROPICAL_RAINFOREST"
          - "DESERT"
          - "MOUNTAIN"
          - "TROPICAL_FARM"
      garden_type_id:
        type: "integer"
        format: "int64"
  Accessory:
    type: "object"
    allOf:
      - $ref: "#/definitions/InventoryItem"
